backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "create(cms-admin): {{collection}}"
    update: "update(cms-admin): {{collection}}"
    delete: "delete(cms-admin): {{collection}}"
    uploadMedia: "[skip ci] upload(cms-admin): “{{path}}”"
    deleteMedia: "[skip ci] delete(cms-admin): “{{path}}”"

locale: 'ru'
media_folder: static/media
public_folder: /media

collections:
  - label: Страницы
    name: pages
    editor:
      preview: false
    files:
      - file: src/markdown/pages/index.md
        label: Главная страница
        name: index
        fields:
          - {
              label: ID,
              name: id,
              widget: string,
              default: index-page,
              pattern: ['index-page', Это поле нельзя менять],
            }
          - {
              label: Первый экран,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Заголовок, name: title, widget: string },
                  { label: Описание, name: description, widget: text },
                  { label: Изображение, name: image, widget: image }
                ],
            }
          - {
              label: Преимущества,
              name: benefits,
              widget: list,
              fields:
                [
                  { label: Преимущество, name: title, widget: string },
                  { label: Описание, name: description, widget: text },
                  { label: Изображение, name: image, widget: image },
                  {
                    label: Теги,
                    name: tags,
                    widget: list,
                    fields: [
                      { label: Тег, name: tag, widget: string },
                    ],
                  },
                ],
            }
          - {
              label: Тренер,
              name: coach,
              widget: object,
              fields:
                [
                  { label: Имя, name: name, widget: string },
                  { label: Описание, name: description, widget: text, required: false, default: '' },
                  { label: Фото, name: photo, widget: image },
                  { label: Фон, name: background, widget: image },
                ],
            }
          - {
              label: Вопросы,
              name: qa,
              widget: list,
              fields: [
                { label: Вопрос, name: question, widget: string },
                { label: Ответ, name: answer, widget: text },
              ],
            }
          - {
              label: Целевой баннер,
              name: target-banner,
              widget: object,
              fields: [
                { label: Текст, name: text, widget: text },
                { label: Текст кнопки, name: button, widget: string },
                { label: Изображение фона, name: bg-image, widget: image },
              ],
            }

      - file: src/markdown/pages/about.md
        label: О нас
        name: about
        fields:
          - {
              label: ID,
              name: id,
              widget: string,
              default: about-page,
              pattern: ['about-page', Это поле нельзя менять],
            }
          - { label: Заголовок, name: title, widget: string }
          - { label: Текст, name: body, widget: markdown }

  - label: Параметры
    name: params
    editor:
      preview: false
    files:
    - file: src/markdown/params/common-info.md
      label: Общая информация
      name: common-info
      fields:
        - {
            label: ID,
            name: id,
            widget: string,
            default: common-info,
            pattern: ['common-info', Это поле нельзя менять],
          }
        - {
            label: Номер телефона,
            name: tel-number,
            widget: string,
          }
        - {
            label: Расписание,
            name: plan,
            widget: string,
          }
        - {
            label: Стоимость,
            name: price,
            widget: string,
          }
        - {
            label: Локация,
            name: location,
            widget: object,
            fields:
              [
                { label: Адрес, name: address, widget: text },
                {
                  label: Координаты,
                  name: coordinates,
                  widget: object,
                  fields:
                    [
                      { label: Широта, name: coordinatesX, widget: string },
                      { label: Долгота, name: coordinatesY, widget: string },
                    ],
                },
              ],
          }
        - {
            label: Соц. сети,
            name: socials,
            widget: list,
            fields:
              [
                { label: Название, name: name, widget: string },
                { label: Логин, name: login, widget: string },
                { label: Ссылка, name: href, widget: string },
              ],
          }
        - {
            label: Логотип,
            name: logo,
            widget: image,
          }
    - file: src/markdown/params/theme.md
      label: Тема
      name: theme
      fields:
        - {
            label: ID,
            name: id,
            widget: string,
            default: theme,
            pattern: ['theme', Это поле нельзя менять],
          }
        - {
            label: Цвет,
            name: colors,
            widget: object,
            fields: [
              { label: Фоновый, name: bgColor, widget: color },
              { label: Основной, name: mainColor, widget: color },
              { label: Акцентирующий, name: accentuatingColor, widget: color },
              { label: Текст, name: textColor, widget: color },
            ],
          }
    - file: src/markdown/params/seo.md
      label: SEO-оптимизация (для поисковиков и соц. сетей)
      name: seo
      fields:
        - {
            label: ID,
            name: id,
            widget: string,
            default: seo,
            pattern: ['seo', Это поле нельзя менять],
          }
        - {
            label: Заголовок (title),
            name: seoTitle,
            widget: string,
          }
        - {
            label: Описание (description),
            name: seoDescription,
            widget: text,
          }
        - {
            label: URL сайта,
            name: seoUrl,
            widget: string,
            required: false,
          }
        - {
            label: Изображение,
            name: seoImage,
            widget: image,
            required: false,
          }
