backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}}"
    update: "Update {{collection}}"
    delete: "Delete {{collection}}"
    uploadMedia: "[skip ci] Upload"
    deleteMedia: "[skip ci] Delete"

locale: 'ru'
media_folder: static/media
public_folder: /media

collections:
  - label: Страницы
    name: pages
    files:
      - file: src/markdown-data/pages/index.md
        label: Главная страница
        name: index
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Первый экран,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Заголовок, name: title, widget: string },
                  { label: Описание, name: description, widget: text },
                  { label: Изображение, name: image, widget: image }
                ],
            }
          - {
              label: Преимущества,
              name: benefits,
              widget: list,
              fields:
                [
                  { label: Преимущество, name: title, widget: string },
                  { label: Изображение, name: image, widget: image },
                  { label: Описание, name: description, widget: text },
                  { label: Tags, name: tags, widget: list },
                ],
            }
          - {
              label: Вопросы,
              name: qa,
              widget: list,
              fields:
                [
                  { label: Вопрос, name: question, widget: string },
                  { label: Ответ, name: answer, widget: text },
                ],
            }
          - {
              label: Баннер целевого действия,
              name: target-banner,
              widget: text,
            }

      - file: src/markdown-data/pages/about.md
        label: О нас
        name: about
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Заголовок, name: title, widget: string }
          - { label: Текст, name: body, widget: markdown }

  - label: Параметры
    name: params
    files:
    - file: src/markdown-data/params/common-info.md
      label: Общая информация
      name: common-info
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "common-info",
          }
        - {
            label: Номер телефона,
            name: tel-number,
            widget: string,
          }
        - {
            label: Локация,
            name: location,
            widget: object,
            fields:
              [
                { label: Адрес, name: address, widget: string },
                {
                  label: Координаты,
                  name: coordinates,
                  widget: list,
                  max: 2,
                  min: 2,
                  fields:
                    [
                      { label: Широта, name: coordinatesX, widget: string },
                      { label: Долгота, name: coordinatesY, widget: string },
                    ],
                },
              ],
          }
        - {
            label: Соц. сети,
            name: socials,
            widget: list,
            fields:
              [
                { label: Логин, name: login, widget: string },
                { label: Ссылка, name: href, widget: string },
              ],
          }
    - file: src/markdown-data/params/seo.md
      label: СЕО-оптимизация
      name: seo
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "seo",
          }
